version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: corporate_stack_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: corporate_stack_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - corporate_stack_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d corporate_stack_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: corporate_stack_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@corporatestack.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - corporate_stack_network
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: corporate_stack_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - corporate_stack_network
    command: redis-server --appendonly yes --requirepass redis123

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local

networks:
  corporate_stack_network:
    driver: bridge
